default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: framecircle_development

test:
  <<: *default
  database: framecircle_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  # Solid Cable expects this
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  # Solid Queue expects this
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
