# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: framecircle_development

test:
  <<: *default
  database: framecircle_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
